// Generated by CoffeeScript 1.6.3
var Asset;

Asset = (function() {
  var assets;

  function Asset() {}

  assets = {};

  Asset.load = function(name, width, height, rows, cols, path, baseTexture) {
    var tHeight, tWidth, textures, x, y, _i, _j, _ref, _ref1;
    if (path == null) {
      path = null;
    }
    if (baseTexture == null) {
      baseTexture = null;
    }
    if (assets[name]) {
      return assets[name];
    }
    baseTexture || (baseTexture = PIXI.BaseTexture.fromImage(path));
    baseTexture.width = width;
    baseTexture.height = height;
    tWidth = width / cols;
    tHeight = height / rows;
    textures = [];
    for (y = _i = 0, _ref = rows - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; y = 0 <= _ref ? ++_i : --_i) {
      for (x = _j = 0, _ref1 = cols - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; x = 0 <= _ref1 ? ++_j : --_j) {
        textures.push(new PIXI.Texture(baseTexture, {
          x: x * tWidth,
          y: y * tHeight,
          width: tWidth,
          height: tHeight
        }));
      }
    }
    return assets[name] = {
      w: width,
      h: height,
      textures: textures
    };
  };

  Asset.movie = function(name, speed, looop, play, textures) {
    var asset, movie;
    asset = assets[name];
    textures || (textures = asset.textures);
    movie = new PIXI.MovieClip(textures);
    movie.width = asset.w;
    movie.height = asset.w;
    movie.anchor.x = 0.5;
    movie.anchor.y = 0.5;
    movie.animationSpeed = speed;
    movie.loop = looop;
    if (play) {
      movie.play();
    }
    return movie;
  };

  return Asset;

})();
