// Generated by CoffeeScript 1.6.3
var Asset;

Asset = (function() {
  Asset.assets = {};

  function Asset(options) {
    this.w = options.w;
    this.h = options.h;
    this.tw = options.tw;
    this.th = options.th;
    this.cols = options.cols;
    this.rows = options.rows;
    this.textures = options.textures;
  }

  Asset.prototype.row = function(row) {
    return this.textures.slice(row * this.cols, +((row * this.cols) + this.cols) + 1 || 9e9);
  };

  Asset.load = function(name, width, height, rows, cols, path, baseTexture) {
    var tHeight, tWidth, textures, x, y, _i, _j, _ref, _ref1;
    if (path == null) {
      path = null;
    }
    if (baseTexture == null) {
      baseTexture = null;
    }
    if (this.assets[name]) {
      return this.assets[name];
    }
    baseTexture || (baseTexture = PIXI.BaseTexture.fromImage(path));
    baseTexture.width = width;
    baseTexture.height = height;
    tWidth = width / cols;
    tHeight = height / rows;
    textures = [];
    for (y = _i = 0, _ref = rows - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; y = 0 <= _ref ? ++_i : --_i) {
      for (x = _j = 0, _ref1 = cols - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; x = 0 <= _ref1 ? ++_j : --_j) {
        textures.push(new PIXI.Texture(baseTexture, {
          x: x * tWidth,
          y: y * tHeight,
          width: tWidth,
          height: tHeight
        }));
      }
    }
    return this.assets[name] = new this({
      w: width,
      h: height,
      tw: tWidth,
      th: tHeight,
      cols: cols,
      rows: rows,
      textures: textures
    });
  };

  Asset.movie = function(name, speed, looop, play, textures) {
    var asset, movie;
    asset = this.assets[name];
    if (!asset) {
      throw "Unknown asset: " + name;
    }
    textures || (textures = asset.textures);
    movie = new PIXI.MovieClip(textures);
    movie.width = asset.tw;
    movie.height = asset.th;
    movie.anchor.x = 0.5;
    movie.anchor.y = 0.5;
    movie.animationSpeed = speed;
    movie.loop = looop;
    if (play) {
      movie.play();
    }
    return movie;
  };

  Asset.preload = function() {
    this.load("explode0", 112, 16, 1, 7, "assets/shared/graphics/explode0.png");
    this.load("explode1", 288, 288, 6, 6, "assets/shared/graphics/explode1.png");
    this.load("bullets", 20, 50, 10, 4, "assets/shared/graphics/bullets.png");
    this.load("ship0", 360, 144, 4, 10, "assets/shared/graphics/ship0.png");
    return this.load("ship1", 360, 144, 4, 10, "assets/shared/graphics/ship1.png");
  };

  return Asset;

})();
