// Generated by CoffeeScript 1.6.3
var BulletView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BulletView = (function(_super) {
  var asset;

  __extends(BulletView, _super);

  View.extended(BulletView, "Projectiles");

  asset = Asset.load("bullets", 20, 50, 10, 4, "assets/shared/graphics/bullets.png");

  function BulletView(bullet) {
    var movie, row;
    row = bullet.level;
    if (bullet.bouncing) {
      row += 5;
    }
    movie = Asset.movie("bullets", 0.5, true, true, asset.textures[row]);
    BulletView.__super__.constructor.call(this, bullet, movie);
  }

  return BulletView;

})(View);
