// Generated by CoffeeScript 1.6.3
var EffectView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

EffectView = (function(_super) {
  __extends(EffectView, _super);

  function EffectView(entity) {
    var _this = this;
    entity.movie.onComplete = function() {
      return entity.expire();
    };
    EffectView.__super__.constructor.call(this, entity, entity.movie);
  }

  return EffectView;

})(View);
