// Generated by CoffeeScript 1.6.3
var Map;

Map = (function() {
  function Map() {}

  Map.prototype.spriteWidth = 16;

  Map.prototype.spriteHeight = 16;

  Map.prototype.mapWidth = 1024;

  Map.prototype.mapHeight = 1024;

  Map.prototype.mapWidthP = 1024 * Map.spriteWidth;

  Map.prototype.mapHeightP = 1024 * Map.spriteHeight;

  Map.load = function(callback) {
    var oReq,
      _this = this;
    oReq = new XMLHttpRequest();
    oReq.open("GET", "assets/arenas/trench9.lvl", true);
    oReq.responseType = "arraybuffer";
    oReq.onload = function(oEvent) {
      var bmpData, tiles, _ref;
      _ref = _this.parseLevel(oEvent), bmpData = _ref[0], tiles = _ref[1];
      return callback(bmpData, tiles);
    };
    return oReq.send(null);
  };

  Map.parseLevel = function(oEvent) {
    var a, arrayBuffer, bmpLength, bmp_data, bmp_size;
    arrayBuffer = oEvent.target.response;
    if (!arrayBuffer) {
      return [];
    }
    bmpLength = restruct.int32lu("length");
    a = new Uint8Array(arrayBuffer);
    bmp_size = bmpLength.unpack(a.subarray(2, 6)).length;
    bmp_data = a.subarray(0, bmp_size);
    return [bmp_data, Tile.fromFile(a, bmp_size, this)];
  };

  return Map;

})();
