// Generated by CoffeeScript 1.6.3
var Scene;

Scene = (function() {
  Scene.prototype.stage = null;

  Scene.prototype.renderer = null;

  Scene.prototype.layers = {};

  Scene.prototype.views = {};

  Scene.prototype.debug = document.getElementById('debug');

  Scene.prototype.layerOrder = ["Starfield", "Map", "Projectiles", "Other ships", "Selfship", "Effects", "HUD"];

  function Scene(game, client) {
    var doc, name, _i, _len, _ref;
    this.game = game;
    this.client = client;
    this.initPixi();
    _ref = this.layerOrder;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      name = _ref[_i];
      doc = new PIXI.DisplayObjectContainer();
      this.stage.addChild(doc);
      this.layers[name] = doc;
    }
    this.width = document.body.clientWidth;
    this.height = window.innerHeight;
    this.viewport = new Viewport(this.width, this.height);
    this.viewport.pos = game.ship.pos;
    this.starfield = new Starfield(this.layers["Starfield"], this.viewport);
  }

  Scene.prototype.initPixi = function() {
    this.stage = new PIXI.Stage(0, false);
    this.renderer = PIXI.autoDetectRenderer(this.width, this.height, document.createElement('canvas'), false, false);
    this.renderer.view.style.position = "absolute";
    this.renderer.view.style.top = "0px";
    this.renderer.view.style.left = "0px";
    document.body.appendChild(this.renderer.view);
    return $(window).resize(function() {
      this.width = document.body.clientWidth;
      this.height = window.innerHeight;
      return this.renderer.resize(this.width, this.height);
    });
  };

  Scene.prototype.step = function(game, timestamp, delta_s) {
    var hash, view, _i, _j, _len, _len1, _ref, _ref1, _results;
    this.viewport.extent();
    this.starfield.update();
    _ref = this.views;
    for (view = _i = 0, _len = _ref.length; _i < _len; view = ++_i) {
      hash = _ref[view];
      view.displayed = false;
    }
    game.simulator.staticTree.searchExpand(this.viewport._extent, 16, 16, this.updateEntity, this);
    game.simulator.dynamicTree.searchExpand(this.viewport._extent, 16, 16, this.updateEntity, this);
    this.renderer.render(this.stage);
    _ref1 = this.views;
    _results = [];
    for (view = _j = 0, _len1 = _ref1.length; _j < _len1; view = ++_j) {
      hash = _ref1[view];
      if (!view.displayed) {
        view.remove();
        _results.push(delete this.views[hash]);
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  Scene.prototype.updateEntity = function(entity) {
    var updated, view, _base, _name;
    view = (_base = this.views)[_name = entity.hash] || (_base[_name] = View.build(this, entity));
    updated = view.update(this.viewport);
    if (!updated) {
      view.remove();
      return delete this.views[entity.hash];
    }
  };

  Scene.prototype.objects = function() {
    var layer, name, sum, _i, _len, _ref;
    sum = 0;
    _ref = this.layers;
    for (layer = _i = 0, _len = _ref.length; _i < _len; layer = ++_i) {
      name = _ref[layer];
      sum += layer.children.length;
    }
    return sum;
  };

  return Scene;

})();
