// Generated by CoffeeScript 1.6.3
var ShipView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ShipView = (function(_super) {
  __extends(ShipView, _super);

  View.extended(ShipView, "Other ships");

  function ShipView(entity) {
    var movie;
    movie = Asset.movie("ship" + entity.options.ship, 0, false, false);
    ShipView.__super__.constructor.call(this, entity, movie);
  }

  ShipView.prototype.update = function(viewport) {
    var i, texture;
    ShipView.__super__.update.call(this, viewport);
    if (this.entity.player) {
      this.displayObject.position.x = viewport.hw;
      this.displayObject.position.y = viewport.hh;
    }
    texture = Math.round((this.entity.angle * this.displayObject.textures.length) / (2 * Math.PI));
    i = Math.mod(texture, this.displayObject.textures.length);
    this.displayObject.gotoAndStop(i);
    return true;
  };

  ShipView.prototype.layerFor = function(scene, entity) {
    if (entity.player) {
      return "Selfship";
    } else {
      return "Other ships";
    }
  };

  return ShipView;

})(View);
