// Generated by CoffeeScript 1.6.3
var TileView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

TileView = (function(_super) {
  var baseTexture, textures;

  __extends(TileView, _super);

  TileView.spriteMapWidth = 19;

  TileView.spriteMapHeight = 10;

  baseTexture = null;

  textures = [];

  function TileView(tile) {
    var displayObject, texture;
    if (!(texture = Asset.assets[tile.index])) {
      return;
    }
    displayObject = new PIXI.Sprite(texture);
    displayObject.anchor.x = 0.5;
    displayObject.anchor.y = 0.5;
    TileView.__super__.constructor.call(this, tile, displayObject);
  }

  TileView.load = function(bmpData) {
    var bmp, canvas;
    bmp = new BMPImage(bmpData.buffer);
    canvas = document.createElement("canvas");
    canvas.name = "tileset";
    bmp.drawToCanvas(canvas);
    return Asset.load("tiles", 304, 160, this.spriteMapHeight, this.spriteMapWidth, null, new PIXI.BaseTexture(canvas));
  };

  return TileView;

})(View);
