// Generated by CoffeeScript 1.6.3
var Viewport,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Viewport = (function(_super) {
  __extends(Viewport, _super);

  function Viewport(w, h) {
    Viewport.__super__.constructor.call(this, null, null, null, null, w, h);
  }

  return Viewport;

})(Entity);
