// Generated by CoffeeScript 1.6.3
var View;

View = (function() {
  var layerMap, objectCounter, viewMap;

  View.prototype.doPos = new Vector2d(0, 0);

  viewMap = {};

  layerMap = {};

  View.prototype.layer = null;

  View.prototype.displayed = false;

  View.prototype.hash = 0;

  objectCounter = 0;

  View.extended = function(klass, layer) {
    viewMap[klass.name.replace(/View/, '')] = klass;
    return layerMap[klass.name] = layer;
  };

  View.build = function(scene, entity) {
    var layerName, view;
    view = new viewMap[entity.constructor.name](entity);
    if (!view.displayObject) {
      return view;
    }
    layerName = view.layerFor(scene, entity);
    view.layer = scene.layers[layerName];
    view.layer.addChild(view.displayObject);
    return view;
  };

  function View(entity, displayObject) {
    this.entity = entity;
    this.displayObject = displayObject;
    this.hash = (objectCounter += 1);
  }

  View.prototype.update = function(viewport) {
    if (!this.entity) {
      return false;
    }
    if (!this.entity.alive()) {
      return false;
    }
    if (!this.displayObject) {
      return false;
    }
    this.doPos.clear().add(this.entity.pos).sub(viewport._extent.ul);
    this.displayObject.position.x = this.doPos.x;
    this.displayObject.position.y = this.doPos.y;
    return true;
  };

  View.prototype.layerFor = function(scene, entity) {
    return layerMap[this.constructor.name];
  };

  View.prototype.remove = function() {
    if (!this.layer) {
      return;
    }
    if (!this.displayObject) {
      return;
    }
    return this.layer.removeChild(this.displayObject);
  };

  return View;

})();
