// Generated by CoffeeScript 1.6.3
var ArrayTree;

ArrayTree = (function() {
  function ArrayTree() {
    this.array = [];
  }

  ArrayTree.prototype.insert = function(data) {
    return this.array.push(data);
  };

  ArrayTree.prototype.search = function(x1, y1, x2, y2) {
    var results, tile, _i, _len, _ref, _ref1, _ref2;
    results = [];
    _ref = this.array;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      tile = _ref[_i];
      if ((x1 <= (_ref1 = tile.pos.x) && _ref1 <= x2)) {
        if ((y1 <= (_ref2 = tile.pos.y) && _ref2 <= y2)) {
          results.push(tile);
        }
      }
    }
    return results;
  };

  ArrayTree.prototype.searchExpand = function(extent, x, y) {
    return this.search(extent.west - x, extent.north - y, extent.east + x, extent.south + y);
  };

  ArrayTree.prototype.searchExtent = function(extent) {
    return this.search(extent.west, extent.north, extent.east, extent.south);
  };

  return ArrayTree;

})();
