// Generated by CoffeeScript 1.6.3
var Bullet,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Bullet = (function(_super) {
  __extends(Bullet, _super);

  Bullet.prototype.bounciness = 1;

  Bullet.prototype.friction = 0;

  Bullet.prototype.damage = 200;

  Bullet.prototype.speed = 100;

  Bullet.prototype.w = 5;

  Bullet.prototype.h = 5;

  function Bullet(ship, simulator, level, bouncing) {
    this.ship = ship;
    this.simulator = simulator;
    this.level = level;
    this.bouncing = bouncing;
    this.lifetime = 10;
    Bullet.__super__.constructor.call(this, simulator, new Vector2d(0, 0).add(ship.pos).addPolar(ship.hw, ship.angle), new Vector2d(0, 0).add(ship.vel).addPolar(this.speed, ship.angle), this.w, this.h);
  }

  Bullet.prototype.collide = function(object) {
    if (object.constructor === Tile) {
      if (object.index === 170) {
        return;
      } else if (this.bouncing) {
        Bullet.__super__.collide.call(this, object);
      }
    }
    if (object.constructor === Ship && object !== this.ship) {
      object.onDamage(this, this.damage);
      this.expire();
      return Effect.create('explode0', this.pos, null);
    }
  };

  Bullet.prototype.simulate = function(delta_s) {
    if (this.ship.safe) {
      this.expire();
    }
    return Bullet.__super__.simulate.call(this, delta_s);
  };

  return Bullet;

})(Entity);
