// Generated by CoffeeScript 1.6.3
var Effect,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Effect = (function(_super) {
  __extends(Effect, _super);

  Effect.prototype.movie = null;

  function Effect(pos, vel, width, height, movie) {
    this.movie = movie;
    Effect.__super__.constructor.call(this, Simulator.simulator, pos, vel, width, height);
  }

  Effect.create = function(name, pos, vel) {
    var movie;
    movie = Asset.movie(name, 0.5, false, true);
    return new this(pos, vel, movie.width, movie.height, movie);
  };

  Effect.prototype.collide = function() {};

  return Effect;

})(Entity);
