// Generated by CoffeeScript 1.6.3
var Extent, Vector2d;

Vector2d = require("./Vector2d.js");

Extent = (function() {
  function Extent(x1, y1, x2, y2) {
    this.ul = new Vector2d(x1, y1);
    this.lr = new Vector2d(x2, y2);
  }

  Extent.prototype.expand = function(x, y) {
    this.ul.subXY(x, y);
    this.lr.addXY(x, y);
    return this;
  };

  Extent.prototype.add = function(extent) {
    if (!extent) {
      debugger;
    }
    this.ul.add(extent.ul);
    this.lr.add(extent.lr);
    return this;
  };

  Extent.prototype.surrounds = function(extent) {
    return this.ul.x <= extent.ul.x && this.ul.y <= extent.ul.y && this.lr.x >= extent.lr.x && this.lr.y >= extent.lr.y;
  };

  Extent.prototype.minmax = function(extent) {
    this.ul.x = Math.min(this.ul.x, extent.ul.x);
    this.ul.y = Math.min(this.ul.y, extent.ul.y);
    this.lr.x = Math.max(this.lr.x, extent.lr.x);
    this.lr.y = Math.max(this.lr.y, extent.lr.y);
    return this;
  };

  Extent.prototype.clear = function() {
    this.ul.clear();
    this.lr.clear();
    return this;
  };

  Extent.prototype.reset = function() {
    this.ul.reset();
    this.lr.reset();
    return this;
  };

  return Extent;

})();

module.exports = Extent;
