// Generated by CoffeeScript 1.6.3
var Map;

Map = (function() {
  function Map(oEvent) {
    var _ref;
    _ref = this.parseLevel(oEvent), this.tileset = _ref[0], this.tiles = _ref[1];
    this.spriteWidth = this.spriteHeight = 16;
    this.spriteMapWidth = 19;
    this.spriteMapHeight = 10;
    this.mapWidth = this.mapHeight = 1024;
    this.mapWidthP = this.mapHeightP = 1024 * this.spriteWidth;
  }

  Map.prototype.tilesInView = function(viewport, ship) {
    var east, north, south, tile, west, _i, _len, _ref, _ref1, _ref2, _results;
    west = ship.x - viewport.width / 2;
    north = ship.y - viewport.height / 2;
    east = ship.x + viewport.width / 2;
    south = ship.y + viewport.height / 2;
    _ref = this.tiles;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      tile = _ref[_i];
      if ((west - 16 <= (_ref1 = tile.x) && _ref1 <= east) && (north - 16 <= (_ref2 = tile.y) && _ref2 <= south)) {
        _results.push(tile);
      }
    }
    return _results;
  };

  Map.prototype.draw = function(viewport, ship, tiles, ctx) {
    var tile, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = tiles.length; _i < _len; _i++) {
      tile = tiles[_i];
      _results.push(this.drawTile(viewport, ship, ctx, tile));
    }
    return _results;
  };

  Map.prototype.drawTile = function(viewport, ship, ctx, tile) {
    var args, col, info, origin, row, smxp, smyp, vpmxp, vpmyp;
    origin = {
      x: ship.x - viewport.width / 2,
      y: ship.y - viewport.height / 2
    };
    row = tile.index / this.spriteMapWidth | 0;
    col = tile.index % this.spriteMapWidth;
    smxp = col * this.spriteWidth;
    smyp = row * this.spriteHeight;
    vpmxp = tile.x - origin.x - 8;
    vpmyp = tile.y - origin.y - 8;
    args = [this.tileset, smxp, smyp, this.spriteWidth, this.spriteHeight, vpmxp, vpmyp, this.spriteWidth, this.spriteHeight];
    info = {
      smxp: smxp,
      smyp: smyp,
      vpmxp: vpmxp,
      vpmyp: vpmyp,
      tile: tile.index,
      x: tile.x,
      y: tile.y
    };
    ctx.drawImage.apply(ctx, args);
    return info;
  };

  Map.prototype.parseLevel = function(oEvent) {
    var a, arrayBuffer, bmp, bmpLength, bmp_data, bmp_size, bytes, canvas, i, index, mapStruct, struct, tiles, tx, ty, x, y;
    arrayBuffer = oEvent.target.response;
    if (!arrayBuffer) {
      return [];
    }
    bmpLength = restruct.int32lu("length");
    mapStruct = restruct.int32lu("struct");
    tiles = [];
    a = new Uint8Array(arrayBuffer);
    bmp_size = bmpLength.unpack(a.subarray(2, 6)).length;
    bmp_data = a.subarray(0, bmp_size);
    bmp = new BMPImage(bmp_data.buffer);
    canvas = document.createElement("canvas");
    canvas.name = "tileset";
    bmp.drawToCanvas(canvas);
    i = bmp_size;
    while (i < a.length) {
      bytes = a.subarray(i, i + 4);
      struct = mapStruct.unpack(bytes).struct;
      tx = struct & 0x03FF;
      ty = (struct >>> 12) & 0x03FF;
      x = tx * 16 + 8;
      y = ty * 16 + 8;
      index = struct >>> 24;
      tiles.push({
        tx: tx,
        ty: ty,
        x: x,
        y: y,
        min: {
          x: x - 8,
          y: y - 8
        },
        max: {
          x: x + 8,
          y: y + 8
        },
        w: 16,
        h: 16,
        index: index - 1,
        meta: [i, length, bytes, struct, struct.toString(2)]
      });
      i += 4;
    }
    return [canvas, tiles];
  };

  return Map;

})();
