// Generated by CoffeeScript 1.6.3
var Starfield;

Starfield = (function() {
  function Starfield() {
    this.tilesize = 1024 * 2;
    this.density = 32 * 4;
    this.levels = [this.generateTile(2, [184, 184, 184]), this.generateTile(3, [96, 96, 96]), this.generateTile(4, [52, 52, 52]), this.generateTile(5, [30, 30, 30]), this.generateTile(6, [19, 19, 19])];
  }

  Starfield.prototype.generateTile = function(ratio, color) {
    var buffer, ctx, d, i, id, points, x, y;
    buffer = document.createElement('canvas');
    buffer.width = this.tilesize;
    buffer.height = this.tilesize;
    ctx = buffer.getContext('2d');
    ctx.webkitImageSmoothingEnabled = false;
    points = (function() {
      var _i, _ref, _results;
      _results = [];
      for (i = _i = 0, _ref = this.density * (Math.pow(ratio, 2)); 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        x = Math.random() * this.tilesize;
        y = Math.random() * this.tilesize;
        id = ctx.createImageData(1, 1);
        d = id.data;
        d[0] = color[0];
        d[1] = color[1];
        d[2] = color[2];
        d[3] = 255;
        ctx.putImageData(id, x, y);
        _results.push([x, y]);
      }
      return _results;
    }).call(this);
    return {
      _buffer: buffer,
      points: points,
      color: color,
      ratio: ratio
    };
  };

  Starfield.prototype.draw = function(viewport, ship, ctx) {
    var level, _i, _len, _ref, _results;
    _ref = this.levels;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      level = _ref[_i];
      _results.push(this.drawLevel(viewport, ship, ctx, level));
    }
    return _results;
  };

  Starfield.prototype.drawLevel = function(viewport, ship, ctx, level) {
    var bottom, col, left, pairs, right, row, tileX, tileY, top, x, y, _i, _j;
    left = Math.floor(((ship.x / level.ratio) - (viewport.width / 2)) / this.tilesize);
    top = Math.floor(((ship.y / level.ratio) - (viewport.height / 2)) / this.tilesize);
    right = Math.ceil(((ship.x / level.ratio) + (viewport.width / 2)) / this.tilesize);
    bottom = Math.ceil(((ship.y / level.ratio) + (viewport.height / 2)) / this.tilesize);
    x = -ship.x / level.ratio;
    y = -ship.y / level.ratio;
    pairs = [];
    for (col = _i = left; left <= right ? _i <= right : _i >= right; col = left <= right ? ++_i : --_i) {
      for (row = _j = top; top <= bottom ? _j <= bottom : _j >= bottom; row = top <= bottom ? ++_j : --_j) {
        tileX = col * this.tilesize + x;
        tileY = row * this.tilesize + y;
        ctx.drawImage(level._buffer, tileX, tileY, this.tilesize, this.tilesize);
        pairs.push([col, row]);
      }
    }
    return [left, right, top, bottom];
  };

  return Starfield;

})();
