require([
  "vendor/restruct.js/restruct.js",
  "vendor/jDataView/src/jDataView.js",
  "vendor/jParser/src/jparser.js",
  "vendor/js_bintrees/dist/rbtree.js",

  "build/models/Entity.js",
  "build/models/Physics.js",
  "build/models/ArrayTree.js",
  "build/models/Ship.js",
  "build/models/Vector2d.js",
  "build/models/Bullet.js",
  "build/models/DLinkedList.js",
  "build/models/Extent.js",
  "build/models/Tile.js",
  "build/models/Effect.js",
  "build/models/UBTree.js",
  "build/models/RbushTree.js",
  "build/models/AI.js",
  "build/models/Simulator.js",
  "build/models/Entity.js",
  "build/Game.js"
])
